### ISSUE TITLE
UI Design Concept Branch Notes

### ISSUE THREAD

**Issue by darkhouse01** [EarlTilluck/Advisement_App#10]
A branch to the UI concept has been added, We are still finalizing the logo design and login page. Currently it's a plain white page with a login form.

Also, after logging in, every user is met with the same dashboard (colors are still to be adjusted), however, the content of the dashboard will change depending on the user.

# **Changes made to files**

**Base view**
The base view page (base.html) has been edited to fit the design currently being processed.

**Login View**
The login view page has been edited with a form (completion still in progress).

**Login Controller**
The login controller has been changed to redirect to the User Model method save()

**Home Controller**
Home controller has been changed to redirect when ADMIN users add a user
* newAction()
* createAction()
* successAction()

* destroyAction() added to log out user

**User Model**
The following has been changed to allow the user to login
* authenticate() - $username changed to $user_id

The following has been changed to allow an ADMIN user to add an account
* save()
* validate()

**SQL File**
A default admin user has been added to to sql file
user_id = 00000001
password = 123456n

A student user has been added to to sql file for testing
user_id = 00052358
password = 123456n

# **Files Added**
## **View**
Home Folder
         - addUser.html
         - success.html

## **Public**
**CSS Folder**
     - custom.css
     - fontastic.css
     - grasp_mobile_progress_circle-1.0.0.min.css
     - style.blue.css
     - style.default.css
     - style.green.css
     - style.pink.css
     - style.red.css
     - style.sea.css
     - style.violet.css

**Fonts Folder**
     - dashboard.eot
     - dashboard.svg
     - dashboard.ttf
     - dashboard.woff

**Icons-Reference Folder**
     Fonts Folder
          - dashboard.eot
          - dashboard.svg
          - dashboard.ttf
          - dashboard.woff
     icons-reference.html
     styles.css

**Img Folder**
     - avatar-1.png

**Js Folder**
     - charts-custom.js
     - charts-home.js
     - fonts.js
     - grasp_mobile_progress_circle-1.0.0.min.js
     - hideShowPassword.min.js
     - jquery.validate.js
     - jquery.validate.min.js
     - jquery-3.3.1.min.js
     - script.js

**Vendor Folder (added to public folder for bootstrap)**
      - bootstrap Folder
      - chart.jsFolder
      - font-awesome Folder
      - jquery Folder
      - jquery.cookie Folder
      - jquery-validation Folder
      - malihu-custom-scrollbar-plugin Folder
      - popper.js Folder

# **N.B.**
The main Vendor folder holding composer and twig is not added to this branch as there are too many files to be added. Just copy the Vendor folder from Assignment 1 and  It should work.

**Comment by stacy23** [comment]
Hi what is this? I don't understand.

**Comment by darkhouse01** [comment]
It's the notes on changes made to files in the App for the UI Design Concept branch, along with all files added.

**Comment by stacy23** [comment]
Hey thanks i realised it after going through it.

**Comment by stacy23** [comment]
Also,this is Stacy Mulchan not Miss Stacy Williams.

**Comment by EarlTilluck** [comment]
about the vendor folder, git is set to ignore this folder altogether.
to get files into your vendor folder, just run the composer install command from the readme and you will get download all the dependencies. 

With this set up we don't have to bother tracking these files anymore as everyone will download the same files using the composer json config

**Comment by EarlTilluck** [comment]
The ui branch has been merged with my current branch,
logic_phase_1

however there were some issues:
* I did not get any files from vendor folder
* way to many requests in base page (above 10) see [this website](https://css-tricks.com/one-two-three/)

lets try to keep the website performance reasonable by: 
* limiting the size of css files and merging them together
* removing some js dependencies we don't need
* using **final block** to add js dependencies only on pages we need them for
* using one font instead of 3 or 4, try using web safe fonts if we need more

further changes to the website should be made to the logic_phase_1 branch

**Comment by EarlTilluck** [comment]
![responsive_advme](https://user-images.githubusercontent.com/37227663/39390450-a8b296c2-4a62-11e8-959d-7f71f126096a.PNG)

**Comment by EarlTilluck** [comment]
master branch updated this morning
I reverted back to basic bootstrap because of multiple issues with all the files and content.

You guys can branch of master and try to fix the issues:
* jerky animation 
* ~~not responsive~~ 
* show password button not working 
* 500 server error messages being hidden behind dashboard
* wrong js validate rules for login page (we don't want to hint password definitions here) 
* (test all browsers and check web console for errors and failed network requests)

note that with just bootstrap I'm able to get similar functionality, import the latest sql and log in as a student to see what the page looks like ( there is some copy paste code for a bootstrap collapse) (the page is still a work in progress)

I strongly suggest you keep to bootstrap only and keep the code simple, or we won't finish in time. The website doesn't need a complicated set up. However, you may choose to continue if you see fit. 

Finally, don't make any further changes to controllers or models, PHP team will deal with that, stick to views, The master branch will continue with the basic setup and UI branch can keep merging as the logic gets updated, that way there is no confusion between two teams. (back up your html files)

regards.

**Comment by stacy23** [comment]
Hello there,

I just signed the petition "Education Minister Anthony Garcia: Education
Minister must present a plan for the Education of Special Needs Children in
T&T" and wanted to see if you could help by adding your name.

Our goal is to reach 15,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/gfrLC86FDh

Thanks!
Stacy
